oro_integration:
    form:
        mapping_settings:
            userFilter:
                type:         text
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.userFilter.label
                    tooltip:      orocrmpro.ldap.integration.transport.mapping.userFilter.tooltip
                    required:     true
                    constraints:
                        - NotBlank: ~
                priority:     10
                applicable:   [ldap]
            userMapping:
                type:         orocrmpro_ldap_user_mapping
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.userMapping.label
                    required:     true
                applicable:   [ldap]
                priority:     20
            roleFilter:
                type:         text
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.roleFilter.label
                    tooltip:      orocrmpro.ldap.integration.transport.mapping.roleFilter.tooltip
                    required:     true
                    constraints:
                        - NotBlank: ~
                applicable:   [ldap]
                priority:     30
            roleIdAttribute:
                type:         text
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.roleIdAttribute.label
                    tooltip:      orocrmpro.ldap.integration.transport.mapping.roleIdAttribute.tooltip
                    required:     true
                    constraints:
                        - NotBlank: ~
                applicable:   [ldap]
                priority:     40
            roleUserIdAttribute:
                type:         text
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.roleUserIdAttribute.label
                    required:     true
                    constraints:
                        - NotBlank: ~
                applicable:   [ldap]
                priority:     50
            roleMapping:
                type:         oro_collection
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.roleMapping.label
                    type:         orocrmpro_ldap_role_mapping
                    required:     false
                    handle_primary: false
                    show_form_when_empty: false
                applicable:   [ldap]
                priority:     60
            exportUserObjectClass:
                type:         text
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.exportUserObjectClass.label
                    required:     true
                    constraints:
                        - NotBlank: ~
                applicable:   [ldap]
                priority:     70
            exportUserBaseDn:
                type:         text
                options:
                    label:        orocrmpro.ldap.integration.transport.mapping.exportUserBaseDn.label
                    required:     true
                    constraints:
                        - NotBlank: ~
                applicable:   [ldap]
                priority:     80
