parameters:
    orocrmpro_ldap.form.type.user_mapping_type.class:           OroCRMPro\Bundle\LDAPBundle\Form\Type\UserMappingType
    orocrmpro_ldap.form.type.role_mapping_type.class:           OroCRMPro\Bundle\LDAPBundle\Form\Type\RoleMappingType
    orocrmpro_ldap.form.type.encryption_type.class:             OroCRMPro\Bundle\LDAPBundle\Form\Type\EncryptionType
    orocrmpro_ldap.form.type.ldap_transport_setting.class:      OroCRMPro\Bundle\LDAPBundle\Form\Type\LdapTransportSettingsFormType
    orocrmpro_ldap.form.type.ldap_transport_check_button.class: OroCRMPro\Bundle\LDAPBundle\Form\Type\LdapTransportCheckButton
    orocrmpro_ldap.form.extension.channel_connectors.class:     OroCRMPro\Bundle\LDAPBundle\Form\Extension\ChannelConnectorsExtension

services:
    orocrmpro_ldap.form.type.user_mapping_type:
        class: %orocrmpro_ldap.form.type.user_mapping_type.class%
        arguments:
            - "@doctrine"
            - "@oro_entity_config.provider.importexport"
            - "@oro_entity_config.provider.entity"
        tags:
            - { name: form.type, alias: orocrmpro_ldap_user_mapping }

    orocrmpro_ldap.form.type.role_mapping_type:
        class: %orocrmpro_ldap.form.type.role_mapping_type.class%
        arguments:
            - "@doctrine"
        tags:
            - { name: form.type, alias: orocrmpro_ldap_role_mapping }

    orocrmpro_ldap.form.type.encryption_type:
        class: %orocrmpro_ldap.form.type.encryption_type.class%
        tags:
            - { name: form.type, alias: orocrmpro_ldap_encryption }

    orocrmpro_ldap.form.type.ldap_transport_setting:
        class: %orocrmpro_ldap.form.type.ldap_transport_setting.class%
        tags:
            - { name: form.type, alias: orocrmpro_ldap_ldap_transport_setting_form_type }
        arguments: ["@oro_integration.manager.types_registry"]

    orocrmpro_ldap.form.type.ldap_transport_check_button:
        class: %orocrmpro_ldap.form.type.ldap_transport_check_button.class%
        tags:
            - { name: form.type, alias: orocrmpro_ldap_transport_check_button_type }

    orocrmpro_ldap.form.extension.channel_connectors:
        class: %orocrmpro_ldap.form.extension.channel_connectors.class%
        tags:
            - { name: form.type_extension, alias: oro_integration_channel_form }
