security:
    firewalls:
        main:
            orocrmpro-ldap-organization-form-login:
                csrf_provider:              form.csrf_provider
                check_path:                 oro_user_security_check
                login_path:                 oro_user_security_login
