definitions:
    schedule_organization:
        label:   'Shedule organization'
        enabled: true
        entity:  Oro\Bundle\OrganizationBundle\Entity\Organization
        order:   10
        actions_configuration:
            - '@assign_constant_value':
                attribute: $.commandName
                value: Oro\Bundle\SearchBundle\Command\ReindexCommand::COMMAND_NAME
            - '@tree':
                actions:
                    - '@create_entity':
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        arguments:
                            - $.commandName

triggers:
    schedule_organization:
        -
            event:    update
            priority: 50
            queued:   true
            field:    is_global
