parameters:
  oropro_organization_config.placeholder.filter.class: OroPro\Bundle\OrganizationConfigBundle\Placeholder\PlaceholderFilter
  oropro_organization_config.event_listener.organization_grid_listener.class: OroPro\Bundle\OrganizationConfigBundle\EventListener\OrganizationGridListener
  oropro_organization_config.provider.organization_configuration.form_provider.class: OroPro\Bundle\OrganizationConfigBundle\Provider\OrganizationConfigurationFormProvider
  oropro_organization_config.organization.class: OroPro\Bundle\OrganizationConfigBundle\Config\OrganizationScopeManager
  oropro_organization_config.user.class: OroPro\Bundle\OrganizationConfigBundle\Config\UserOrganizationScopeManager
services:
  oropro_organization_config.placeholder.filter:
      class: %oropro_organization_config.placeholder.filter.class%

  oropro_organization_config.event_listener.organization_grid_listener:
      class: %oropro_organization_config.event_listener.organization_grid_listener.class%
      tags:
          - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.organization-grid, method: onBuildBefore }

  oropro_organization_config.provider.form_provider:
      class: %oropro_organization_config.provider.organization_configuration.form_provider.class%
      arguments:
          - "@oro_config.config_bag"
          - "@form.factory"
          - "@oro_security.security_facade"
      tags:
          -  { name: oro_config.configuration_provider }
      lazy: true

  oropro_organization_config.scope.organization:
      class: %oropro_organization_config.organization.class%
      public: false
      parent: oro_config.scope_manager.abstract
      calls:
          - [setSecurityContext, [ '@security.token_storage' ]]
      tags:
          - { name: oro_config.scope, scope: organization, priority: 0 }

  oropro_organization_config.scope.user:
      class: %oropro_organization_config.user.class%
      public: false
      parent: oro_config.scope_manager.abstract
      calls:
          - [setSecurityContext, [ '@security.token_storage' ]]
      tags:
          - { name: oro_config.scope, scope: user, priority: 256 }
