placeholders:
    view_navButtons_before:
        items:
            organization_config_button: ~

items:
    organization_config_button:
        template: OroProOrganizationConfigBundle:Configuration:button.html.twig
        applicable: "@oropro_organization_config.placeholder.filter->isOrganizationPage($entity$)"
