parameters:
    oropro_user.form.type.role_organization_select.class: OroPro\Bundle\UserBundle\Form\Type\RoleOrganizationSelectType
    oropro_user.autocomplete.role_organization_search_handler.class: OroPro\Bundle\UserBundle\Autocomplete\RoleOrganizationSearchHandler
    oropro_user.event_listener.datagrid.role.class: OroPro\Bundle\UserBundle\EventListener\Datagrid\RoleListener
    oropro_user.acl.voter.role.class: OroPro\Bundle\UserBundle\Acl\Voter\RoleVoter
    oropro_user.helper.class: OroPro\Bundle\UserBundle\Helper\UserProHelper
    oropro_user.form.type.extension.user.class: OroPro\Bundle\UserBundle\Form\Extension\UserTypeExtension

    oro_user.datagrid.datasource.role_permission_datasource.class: OroPro\Bundle\UserBundle\Datagrid\RolePermissionDatasource

services:
    oropro_user.form.type.role_organization_select:
        class: %oropro_user.form.type.role_organization_select.class%
        arguments:
            - "@security.token_storage"
            - "@oropro_user.helper"
            - "@oropro_organization.helper"
        tags:
            - { name: form.type, alias: oropro_user_role_organization_select }

    oropro_user.autocomplete.role_organization_search_handler:
        class: %oropro_user.autocomplete.role_organization_search_handler.class%
        arguments:
            - "@oro_organization.autocomplete.organization_search_handler"
            - "@security.token_storage"
            - "@oropro_organization.helper"
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: oropro_user_role_organizations }
        lazy: true

    oropro_user.event_listener.datagrid.role:
        class: %oropro_user.event_listener.datagrid.role.class%
        arguments:
            - "@oropro_user.helper"
            - "@oropro_organization.helper"
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.roles-grid, method: onBuildBefore }

    oropro_user.acl.voter.role:
        class: %oropro_user.acl.voter.role.class%
        arguments:
            - "@oropro_user.helper"
            - "@oropro_organization.helper"
        tags:
            - { name: security.voter, priority: 100 }

    oropro_user.helper:
        class: %oropro_user.helper.class%
        arguments:
            - "@security.token_storage"

    oropro_user.form.type.extension.user:
        class: %oropro_user.form.type.extension.user.class%
        arguments:
            - "@doctrine"
            - "@translator"
        tags:
            - { name: form.type_extension, alias: oro_user_user }
