oro_system_configuration:
    groups:
        integration_email_settings:
            title: oro_pro_ews.form.email_settings
            icon:  icon-envelope

        integrations_ews:
            title: oro_pro_ews.form.ews

    fields:
        oro_pro_ews.enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 150
            options:
                label: oro_pro_ews.form.is_enabled
                resettable: false
                required: false

        oro_pro_ews.server:
            data_type: string
            type: text
            priority: 100
            options:
                label: oro_pro_ews.form.server
                resettable: false
                required: false

        oro_pro_ews.login:
            data_type: string
            type: text
            priority: 80
            options:
                label: oro_pro_ews.form.login
                resettable: false
                required: false

        oro_pro_ews.password:
            data_type: string
            type: oro_encoded_password
            priority: 70
            options:
                label: oro_pro_ews.form.password
                required: false
                resettable: false

        oro_pro_ews.version:
            data_type: string
            type: choice
            priority: 90
            options:
                label: oro_pro_ews.form.version
                choices:
                    Exchange2007:     Exchange 2007
                    Exchange2007_SP1: Exchange 2007 SP1
                    Exchange2010:     Exchange 2010
                    Exchange2010_SP1: Exchange 2010 SP1
                    Exchange2010_SP2: Exchange 2010 SP2
                    Exchange2013:     Exchange 2013 (or Office 365)
                required: false
                resettable: false

        oro_pro_ews.domain_list:
            data_type: array
            type: oro_textlist
            priority: 60
            options:
                label: oro_pro_ews.form.domains
                tooltip: oro_pro_ews.form.tooltip.domain_list
                resettable: false
                required: false

        oro_pro_ews.check_connection:
            type: oro_pro_ews_check_button
            ui_only: true
            options:
                label: false
                required: false
                resettable: false

    tree:
        system_configuration:
            platform:
                children:
                    integrations:
                        children:
                            integration_email_settings:
                                children:
                                    integrations_ews:
                                        children:
                                            - oro_pro_ews.enabled
                                            - oro_pro_ews.server
                                            - oro_pro_ews.login
                                            - oro_pro_ews.password
                                            - oro_pro_ews.version
                                            - oro_pro_ews.domain_list
                                            - oro_pro_ews.check_connection

    api_tree:
        ews:
            oro_pro_ews.enabled: ~
            oro_pro_ews.server: ~
            oro_pro_ews.login: ~
            oro_pro_ews.version: ~
            oro_pro_ews.domain_list: ~
