datagrid:
    organization-grid:
        extended_entity_name: %oro_organization.organization.entity.class%
        options:
            entityHint: organization
        acl_resource: oro_organization_view
        source:
            type: orm
            query:
                select:
                    - u.id
                    - u.name
                    - u.enabled
                    - u.createdAt
                    - u.updatedAt
                from:
                    - { table: OroOrganizationBundle:Organization, alias: u }
        columns:
            name:
                label: oro.organization.name.label
            enabled:
                label:         oro.user.enabled.label
                frontend_type: select
                choices:
                   - Inactive
                   - Active
            createdAt:
                label: oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label: oro.ui.updated_at
                frontend_type: datetime
        properties:
            id: ~
            update_link:
                type: url
                route: oropro_organization_update
                params:
                    - id
            view_link:
                type: url
                route: oropro_organization_view
                params:
                    - id
        actions:
            view:
                type:          navigate
                label:         oro.grid.action.view
                link:          view_link
                icon:          eye-open
                acl_resource:  oro_organization_view
                rowAction:     true
            update:
                type:          navigate
                label:         oro.grid.action.update
                link:          update_link
                icon:          edit
                acl_resource:  oro_organization_update
        sorters:
            columns:
                name:
                    data_name: u.name
                enabled:
                    data_name: u.enabled
                createdAt:
                    data_name: u.createdAt
                updatedAt:
                    data_name: u.updatedAt
            default:
                name: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: u.name
                enabled:
                    type: boolean
                    data_name: u.enabled
                    options:
                        field_options:
                            choices:
                                2: Inactive
                                1: Active
                createdAt:
                    type: datetime
                    data_name: u.createdAt
                updatedAt:
                    type: datetime
                    data_name: u.updatedAt

    organization-users-grid:
        extends: user-relation-grid
        acl_resource: oro_organization_update
        source:
            query:
                select:
                    - >
                      (CASE WHEN (:organization_id IS NOT NULL) THEN
                        CASE WHEN (:organization_id MEMBER OF u.organizations OR u.id IN (:data_in)) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN u.id IN (:data_in) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as has_organization
            bind_parameters:
                -
                    name: organization_id
                    default: null
        columns:
            has_organization:
                label: oropro.organization.datagrid.has_organization.label
                editable: true
                frontend_type: boolean
            firstName:
                label: oro.user.first_name.label
            lastName:
                label: oro.user.last_name.label
            email:
                label: oro.user.email.label
            username:
                label: oro.user.username.label
            enabled:
                label: oro.user.enabled.label
                frontend_type: select
                choices:
                   - Inactive
                   - Active
        filters:
            columns:
                has_organization:
                    type: boolean
                    data_name: has_organization
                firstName:
                    type: string
                    data_name: u.firstName
                lastName:
                    type: string
                    data_name: u.lastName
                email:
                    type: string
                    data_name: u.email
                username:
                    type: string
                    data_name: u.username
                enabled:
                    type: boolean
                    data_name: u.enabled
                    options:
                        field_options:
                            choices:
                                2: Inactive
                                1: Active
        sorters:
            multiple_sorting: true
            columns:
                has_organization:
                    data_name: has_organization
            default:
                has_organization: DESC
                lastName:         ASC

        options:
            rowSelection:
                dataField:  id
                columnName: has_organization
                selectors:
                    included: '#organizationAppendUsers'
                    excluded: '#organizationRemoveUsers'

    organization-view-users-grid:
        extends: user-relation-grid
        acl_resource: oro_organization_view
        source:
            query:
                where:
                    and:
                        - :organization_id MEMBER OF u.organizations
            bind_parameters:
                - organization_id
        columns:
            firstName:
                label: oro.user.first_name.label
            lastName:
                label: oro.user.last_name.label
            email:
                label: oro.user.email.label
            username:
                label: oro.user.username.label
            enabled:
                label: oro.user.enabled.label
                frontend_type: select
                choices:
                   - Inactive
                   - Active
        sorters:
            default:
                lastName: ASC
        filters:
            columns:
                firstName:
                    type: string
                    data_name: u.firstName
                lastName:
                    type: string
                    data_name: u.lastName
                email:
                    type: string
                    data_name: u.email
                username:
                    type: string
                    data_name: u.username
                enabled:
                    type: boolean
                    data_name: u.enabled
                    options:
                        field_options:
                            choices:
                                2: Inactive
                                1: Active
